export const GET_SIGNED_URL_REQUEST = 'GET_SIGNED_URL_REQUEST'
export const GET_SIGNED_URL_SUCCESS = 'GET_SIGNED_URL_SUCCESS'
export const GET_SIGNED_URL_FAIL = 'GET_SIGNED_URL_FAIL'

export const UPLOAD_FILE_REQUEST = 'UPLOAD_FILE_REQUEST'
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS'
export const UPLOAD_FILE_FAIL = 'UPLOAD_FILE_FAIL'
